# Generated by Django 5.2.1 on 2025-05-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeclass',
            name='free_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='Monday', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freeclass',
            name='free_hour',
            field=models.CharField(choices=[('9-10am', '9-10am'), ('10-11am', '10-11am'), ('11-12am', '11-12am'), ('12-1pm', '12-1pm'), ('1-2pm', '1-2pm'), ('2-3pm', '2-3pm'), ('3-4pm', '3-4pm'), ('4-5pm', '4-5pm')], default='9-10am', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Days',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
