# Generated by Django 5.2.1 on 2025-05-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_freeclass_room_status_freeclass_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeclass',
            name='is_occupied',
            field=models.BooleanField(default=True),
        ),
    ]
