# Generated by Django 5.2.1 on 2025-05-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0004_freeclass_is_occupied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeclass',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
