# Generated by Django 5.2.1 on 2025-05-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0007_freeclass_floor_freeclass_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeclass',
            name='Floor',
            field=models.CharField(choices=[('Ground Floor', 'Ground Floor'), ('1 Floor', '1 Floor'), ('2 Floor', '2 Floor'), ('3 Floor', '3 Floor'), ('4 Floor', '4 Floor'), ('5 Floor', '5 Floor'), ('6 Floor', '6 Floor'), ('7 Floor', '7 Floor'), ('8 Floor', '8 Floor'), ('9 Floor', '9 Floor'), ('10 Floor', '10 Floor')], max_length=20),
        ),
    ]
