# Generated by Django 5.2.1 on 2025-05-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0008_alter_freeclass_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeclass',
            name='Day',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='freeclass',
            name='Floor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='freeclass',
            name='Room_Status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='freeclass',
            name='Room_Type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='freeclass',
            name='Time',
            field=models.CharField(max_length=10),
        ),
    ]
