# Generated by Django 5.2.7 on 2025-10-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0010_alter_freeclass_day_alter_freeclass_room_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeclass',
            name='Day',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='freeclass',
            name='Room_Status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='freeclass',
            name='Room_Type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='freeclass',
            name='Time',
            field=models.CharField(max_length=10),
        ),
    ]
