# Generated by Django 5.2.7 on 2025-11-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0012_alter_freeclass_day_alter_freeclass_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeclass',
            name='Time',
            field=models.CharField(choices=[('9-10am', '9-10am'), ('10-11am', '10-11am'), ('11-12am', '11-12am'), ('12-1pm', '12-1pm'), ('1-2pm', '1-2pm'), ('2-3pm', '2-3pm'), ('3-4pm', '3-4pm'), ('4-5pm', '4-5pm')], max_length=10),
        ),
    ]
