# Generated by Django 5.2.1 on 2025-05-26 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0005_alter_freeclass_is_occupied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freeclass',
            old_name='block',
            new_name='Block',
        ),
        migrations.RenameField(
            model_name='freeclass',
            old_name='free_day',
            new_name='Day',
        ),
        migrations.RenameField(
            model_name='freeclass',
            old_name='room_status',
            new_name='Room_Status',
        ),
        migrations.RenameField(
            model_name='freeclass',
            old_name='room_type',
            new_name='Room_Type',
        ),
        migrations.RenameField(
            model_name='freeclass',
            old_name='free_hour',
            new_name='Time',
        ),
    ]
