# Generated by Django 5.2.1 on 2025-05-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0006_rename_block_freeclass_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeclass',
            name='Floor',
            field=models.CharField(default='Floor', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freeclass',
            name='Room_No',
            field=models.CharField(default='Monday', max_length=10),
            preserve_default=False,
        ),
    ]
