# Generated by Django 5.2.1 on 2025-05-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0009_alter_freeclass_day_alter_freeclass_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeclass',
            name='Day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='freeclass',
            name='Room_Status',
            field=models.CharField(choices=[('Ground Floor', 'Ground Floor'), ('1 Floor', '1 Floor'), ('2 Floor', '2 Floor'), ('3 Floor', '3 Floor'), ('4 Floor', '4 Floor'), ('5 Floor', '5 Floor'), ('6 Floor', '6 Floor'), ('7 Floor', '7 Floor'), ('8 Floor', '8 Floor'), ('9 Floor', '9 Floor'), ('10 Floor', '10 Floor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='freeclass',
            name='Room_Type',
            field=models.CharField(choices=[('classroom', 'Classroom'), ('Computer Lab', 'Computer Lab')], max_length=20),
        ),
        migrations.AlterField(
            model_name='freeclass',
            name='Time',
            field=models.CharField(choices=[('9-10am', '9-10am'), ('10-11am', '10-11am'), ('11-12am', '11-12am'), ('12-1pm', '12-1pm'), ('1-2pm', '1-2pm'), ('2-3pm', '2-3pm'), ('3-4pm', '3-4pm'), ('4-5pm', '4-5pm')], max_length=10),
        ),
    ]
