# Generated by Django 5.2.7 on 2025-11-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0011_alter_freeclass_day_alter_freeclass_room_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeclass',
            name='Day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='freeclass',
            name='Floor',
            field=models.CharField(choices=[('1 Floor', '1 Floor'), ('2 Floor', '2 Floor'), ('3 Floor', '3 Floor'), ('4 Floor', '4 Floor'), ('5 Floor', '5 Floor'), ('6 Floor', '6 Floor'), ('7 Floor', '7 Floor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='freeclass',
            name='Room_Status',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied')], max_length=20),
        ),
        migrations.AlterField(
            model_name='freeclass',
            name='Room_Type',
            field=models.CharField(choices=[('Classroom', 'Classroom'), ('Computer Lab', 'Computer Lab')], max_length=20),
        ),
        migrations.AlterField(
            model_name='freeclass',
            name='Time',
            field=models.CharField(choices=[('9:00', '9:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('1:00', '1:00'), ('2:00', '2:00'), ('3:00', '3:00'), ('4:00', '4:00'), ('5:00', '5:00')], max_length=10),
        ),
    ]
